// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AlunoTurma.Infraestructure.Migrations
{
    [DbContext(typeof(AlunoTurmaDataContext))]
    partial class AlunoTurmaDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("AlunoTurma.Application.Api.Dto.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1L)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Nome");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Password");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("Usuario");

                    b.HasKey("Id");

                    b.ToTable("Aluno", (string)null);
                });

            modelBuilder.Entity("AlunoTurma.Application.Api.Dto.AlunoxTurma", b =>
                {
                    b.Property<int>("AlunoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("aluno_id");

                    b.Property<int>("TurmaId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("turma_id");

                    b.HasKey("AlunoId", "TurmaId");

                    b.HasIndex("TurmaId");

                    b.ToTable("aluno_turma", (string)null);
                });

            modelBuilder.Entity("AlunoTurma.Application.Api.Dto.Turma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1L)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Ano")
                        .HasMaxLength(4)
                        .HasColumnType("INT")
                        .HasColumnName("Ano");

                    b.Property<string>("NomeTurma")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("NVARCHAR")
                        .HasColumnName("NomeTurma");

                    b.HasKey("Id");

                    b.ToTable("Turma", (string)null);
                });

            modelBuilder.Entity("AlunoTurma.Application.Api.Dto.AlunoxTurma", b =>
                {
                    b.HasOne("AlunoTurma.Application.Api.Dto.Aluno", "Aluno")
                        .WithMany("AlunoTurmas")
                        .HasForeignKey("AlunoId")
                        .IsRequired()
                        .HasConstraintName("fk_aluno_turma_1_idx");

                    b.HasOne("AlunoTurma.Application.Api.Dto.Turma", "Turma")
                        .WithMany("AlunoTurmas")
                        .HasForeignKey("TurmaId")
                        .IsRequired()
                        .HasConstraintName("fk_turma_1_idx");

                    b.Navigation("Aluno");

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("AlunoTurma.Application.Api.Dto.Aluno", b =>
                {
                    b.Navigation("AlunoTurmas");
                });

            modelBuilder.Entity("AlunoTurma.Application.Api.Dto.Turma", b =>
                {
                    b.Navigation("AlunoTurmas");
                });
#pragma warning restore 612, 618
        }
    }
}
